# Generated by Django 5.0 on 2024-07-30 12:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Root',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('asgi', models.TextField(blank=True, null=True)),
                ('asgi_context', models.TextField(blank=True, null=True)),
                ('settings', models.TextField(blank=True, null=True)),
                ('settings_context', models.TextField(blank=True, null=True)),
                ('urls', models.TextField(blank=True, null=True)),
                ('urls_context', models.TextField(blank=True, null=True)),
                ('wsgi', models.TextField(blank=True, null=True)),
                ('wsgi_context', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OtpToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(default='ab9214', max_length=6)),
                ('tp_created_At', models.DateTimeField(auto_now_add=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project_root')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('project_description', models.TextField(blank=True, max_length=1000, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project_root')),
            ],
        ),
        migrations.CreateModel(
            name='Startapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200)),
                ('admin', models.TextField(blank=True, null=True)),
                ('admin_context', models.TextField(blank=True, null=True)),
                ('apps', models.TextField(blank=True, null=True)),
                ('apps_context', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('model_context', models.TextField(blank=True, null=True)),
                ('test', models.TextField(blank=True, null=True)),
                ('test_context', models.TextField(blank=True, null=True)),
                ('urls', models.TextField(blank=True, null=True)),
                ('urls_context', models.TextField(blank=True, null=True)),
                ('views', models.TextField(blank=True, null=True)),
                ('views_context', models.TextField(blank=True, null=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project_root')),
            ],
        ),
        migrations.CreateModel(
            name='Static',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project_root')),
            ],
        ),
        migrations.CreateModel(
            name='Js',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('js_name', models.CharField(blank=True, max_length=200, null=True)),
                ('js_data', models.TextField(blank=True, max_length=40000, null=True)),
                ('js_context', models.TextField(blank=True, max_length=4000, null=True)),
                ('static_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.static')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_name', models.CharField(blank=True, max_length=200, null=True)),
                ('images_data', models.ImageField(upload_to='Images')),
                ('static_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.static')),
            ],
        ),
        migrations.CreateModel(
            name='Css',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css_name', models.CharField(blank=True, max_length=200, null=True)),
                ('css_data', models.TextField(blank=True, max_length=40000, null=True)),
                ('css_context', models.TextField(blank=True, max_length=4000, null=True)),
                ('static_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.static')),
            ],
        ),
        migrations.CreateModel(
            name='TableOfContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_structure_graph', models.TextField(blank=True, max_length=1000, null=True)),
                ('screenshot1', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('screenshot2', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('screenshot3', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('screenshot4', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('screenshot5', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('screenshot6', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('screenshot7', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('screenshot8', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('screenshot9', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('screenshot10', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('screenshot11', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('screenshot12', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('screenshot13', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('screenshot14', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('screenshot15', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project_root')),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_name', models.CharField(blank=True, max_length=200, null=True)),
                ('html_data', models.TextField(blank=True, max_length=40000, null=True)),
                ('html_context', models.TextField(blank=True, max_length=4000, null=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project_root')),
            ],
        ),
    ]
